# Przegląd literatury {#sec-lit}

Badania odnośnie wpływu konstrukcji lądów na jakość wód są istotne przez stale rosnącą liczbę ludności, w szczególności w obszarach na wybrzeżach [@mcgranahan2007rising].
Nowe lądy znajdują zastosowania w poszerzaniu granic przybrzeżnych miast, dostarczając tereny pod strefy mieszkalne i przemysłowe [@wang2014development].
Ocena wpływu konstrukcji nowych lądów na stan jakości wód jest tematem wielu badań, których wyniki wykorzystano w tej pracy.
Jakość wody rozumiana jest jako opis charakterystyki wody, określających jej przydatność do wykorzystywania w wielu dziedzinach.
Jakość wody jest oceniana na podstawie fizycznych, chemicznych i biologicznych parametrów [@tyagi2013water].

Zaletą danych teledetekcyjnych w ocenie jakości wód jest zasięg, którym obejmują ciągły obszar badań [@gholizadeh2016comprehensive].
Pozwala to na obserwacje przestrzennego rozkładu stanu wód, w przeciwieństwie do punktowych pomiarów w terenie, które dostarczają informacje jedynie o stanie konkretnego punktu w przestrzeni.
Wykorzystanie zdjęć satelitarnych jako danych teledetekcyjnych ogranicza jednak liczbę właściwości wody, jaką można ocenić.
Pozwalają one głównie na badanie fizycznych właściwości wód, takich jak ich kolor czy mętność [@glasgow2004real].
Stacje pomiarowe w terenie pozwalają na pozyskanie większej ilości informacji, opisujących chemiczne i biologiczne własności wody [@summers2020water].
Znaczna liczba badań zbiorników wodnych przy wykorzystaniu danych teledetekcyjnych skupia się na ocenie występowania chlorofilu a oraz stężenia zawieszonego materiału [@gholizadeh2016comprehensive].

Zespół @zhang2017assessment prowadził badania na obszarze zatoki Jiaozhou w Chinach.
Wybrzeże tej zatoki ulegało przekształceniom, będących wynikiem wielu prac konstrukcji nowych lądów.
Część z nowych terenów wykorzystano do rozwoju przemysłu.
Wraz ze wzrostem natężenia konstrukcji nowych lądów, odnotowano wzrost stężenia nieorganicznego azotu, rozpuszczonego w wodach zatoki Jiaozhou.
W ramach tej pracy, zdecydowano się zbadać wpływ wybranych czynników na zmiany stężenia nieorganicznego azotu w zatoce Jiaozhou, które mogła doprowadzić do zmian jakości wody.
Do oceny jakości wód, zespół pozyskał zbiory danych pochodzące z pomiarów w terenie.
Dane te opisują właściwości wody, których zmiany w stężeniu występowania w wodzie mogą świadczyć o potencjalnym pogorszeniu lub polepszeniu jakości wód.
Do zbioru danych, oprócz stężenia azotu odprowadzanego przez rzeki do zbiornika, zaliczono również informacje o: stężeniu chlorofilu a, zasadowości i temperaturze wody, zasoleniu czy ilości rozpuszczonego tlenu.
Dane następnie podzielono na dwie grupy: czynniki wpływu antropogenicznego (przedostawanie się azotu i innych związków do zbiorników wodnych bezpośrednio przez strefy przemysłowe, lub odprowadzone do rzek uchodzących w zatoce) oraz przyrodnicze czynniki strefy przybrzeżnej (stężenie chlorofilu a i zawiesiny w wodzie, temperatura i zasolenie wody, oraz zjawiska przyrodnicze).
W pracy wykorzystano metody statystyczne, między innymi regresję liniową, analizę czynnikową oraz numeryczne modele jakości wód, do zbadania wpływu poszczególnych elementów zbioru danych na zmiany stężenia rozpuszczonego azotu w zatoce.
Praca wskazała, że głównymi czynnikami pogorszenia jakości wód w zatoce Jiaozhou był wzrost stężenia nieorganicznego azotu odprowadzanego przez rzeki do zatoki, oraz jednoczesne zmniejszanie powierzchni zbiornika wodnego.
Tworzenie nowych lądów w zatoce skutkowało przekształcaniem powierzchni zatoki Jiaozhou między innymi w obszary przemysłowe, które zwiększały stężenie nieorganicznego azotu w wodach zatoki. 
Autorzy wskazali na konieczność wprowadzenia programów uzdatniania wody z rzek, czy przenoszenia stref przemysłowych z dala od wybrzeża w celu poprawienia jakości wód w zbiorniku.

Praca @hao2021effects skupia się na określeniu wpływu konstrukcji nowych terenów w mieście Ningbo na stan jakości wód w zatoce Hangzhou w Chinach.
Do oceny jakości wód wybrano cztery metale ciężkie: miedź, ołów, cynk i kadm.
Wzrost stężenia tych metali w wodzie został utożsamiony z pogorszeniem jakości wody.
Dane pozyskano z próbek, pobranych w trzech okresach: przed rozpoczęciem prac (2007 rok), tuż po zakończeniu prac (2016 rok) i dłuższy czas po zakończeniu prac (2018 rok).
Próbkowanie stężenia metali ciężkich w trzech oddzielnych etapach pozwoliło na ocenę wpływu tworzenia nowych lądów na stan jakości wód, porównując ilość metali ciężkich po zakończeniu prac z ilością przed rozpoczęciem prac.
Badania wskazały na najwyższe wartości trzech z czterech metali ciężkich w 2016 roku, czyli tuż po zakończeniu prac.
Jedynym metalem ciężkim, którego ilość była większa przed rozpoczęciem prac niż tuż po zakończeniu prac był kadm.
Największy wzrost tuż po zakończeniu prac, w porównaniu do stanu przed rozpoczęciem prac, odnotowały miedź oraz cynk.
Obserwując stężenia metali ciężkich w 2018 roku, czyli dwa lata po zakończeniu prac, zauważyć można spadek ich stężenia do stanu przed rozpoczęciem prac.
W przypadku ołowiu, stężenie metali wykryte w zbiorniku było mniejsze w 2018 roku niż w 2007 roku.
Trend spadku stężenia metali po zakończeniu prac nie został odnotowany dla kadmu, którego stężenie w wodzie wzrosło dwa lata po zakończeniu prac.
Wyniki badań wskazują na wpływ tworzenia nowych lądów na stan jakości wody.
Tuż po zakończeniu prac, stężenie metali ciężkich w wodach było większa niż przed rozpoczęciem prac.
Wraz z upływem czasu po zakończeniu prac, stężenie metali w wodzie stopniowo malało.

Praca @wang2023observations skupiona jest na badaniu wpływu budowy lotniska w Hongkongu na jakość pobliskich wód.
Jako, że Hongkong dysponuje ograniczoną ilością terenu, lotnisko zdecydowano się zbudować na nowo utworzonym lądzie.
Do oceny jakości wód autorzy wykorzystali zdjęcia satelitarne Landsat oraz dane, pochodzące z monitoringu terenowego.
Jakość wód została oceniona głównie przy pomocy parametrów stężenia zawiesiny i nieorganicznego azotu w wodzie.
Po wstępnym przetworzeniu zdjęć satelitarnych, wartości poszczególnych kanałów zestawiono z danymi terenowymi.
Pozwoliło to na wybór kanałów widzialnych i bliskiej podczerwieni, na podstawie których obliczono algorytm estymacji parametrów jakości wody.
Algorytmy wykorzystano do stworzenia modeli, pozwalających na oszacowanie stężenia zawiesiny i nieorganicznego azotu na podstawie obrazów satelitarnych.
Modele te były trenowane na podstawie danych terenowych.
Badania wykazały wzrost stężenia zawiesiny i nieorganicznego azotu w pobliżu nowego lądu, na którym znajdowało się lotnisko.
Autorzy potwierdzili wpływ tworzenia nowego lądu, a w szczególności jego wykorzystywania, na stan jakości wód.
