# Materiały {#sec-materialy}

Do oceny stanu jakości wód, wykorzystano dane teledetekcyjne w postaci obrazów satelitarnych.
[@tbl-data_info] zawiera szczegóły odnośnie pozyskanych zdjęć.
Wszystkie obrazy pochodzą z drugiego poziomu programu Landsat Collection 2.
W zależności od lat prowadzonych badań, zdjęcia pochodzą z satelit Landsat 5, 7 lub 8.
Obrazy pozyskano z katalogu Planetary Computer od firmy Microsoft [@microsoft_open_source_2022_7261897].
Wszystkie zdjęcia mają rozdzielczość przestrzenną 30 metrów.

Z pozyskanych zdjęć satelitarnych, do obliczenia wskaźników spektralnych, wykorzystano kanały widzialne (czerwony, zielony, niebieski) i bliskiej podczerwieni.
Wykorzystany został również kanał oceny jakości poszczególnych pikseli do wyboru jedynie obszarów zaklasyfikowanych jako zbiorniki wodne bez pokrycia chmurami.

@tbl-data_info zawiera również informacje o liczbie dostępnych zdjęć dla obszarów badań, pozyskanych z Planetary Computer.
W przypadku Dubaju, Lagosu oraz Szanghaju, obszary badań były wystarczająco duże, że ich obszar dla pojedynczych dni pokrywały dwa zdjęcia satelitarne.
Spowodowało to wzrost ilości dostępnych obrazów dla tych obszarów.
Dla Dubaju i Lagosu jednak, dwa zdjęcia dla tych samych dni pokrywały się tak mocno, że dodatkowy obraz nie dostarczał nowych informacji do obszaru badań. 
Ze wszystkich dostępnych zdjęć dla badanych obszarów wybrano jedynie te, dla których procentowy udział ilości pikseli bez wartości w całym obrazie nie przekroczył wartości progowej.
Wartość progowa zmieniała się dla każdego z obszarów, w zależności od ilości obszarów lądowych znajdujących się w obszarze badań.
Piksele klasyfikowane jako ląd były wykluczane z analizy, w wyniku czego przy dużym udziale lądu należało zwiększyć wartość progową braku wartości.
Oprócz lądów, chmury również wpływały na brak wartości na obrazie satelitarnym.
Przy dużym zachmurzeniu, liczba dostępnych pikseli dla zbiorników wodnych malała, co skutkowało zmniejszeniem przydatności takiego zdjęcia do badań.

Oprócz zdjęć satelitarnych, w pracy wykorzystano również dane o głębokości zbiorników wodnych ze zbioru GEBCO_2023 Grid [@gebco_2023].
Każda komórka rastra zawiera informacje o głębokości w metrach.
Dane o batymetrii zostały wykorzystane do zbadania zmian wartości wskaźników jakości wód wzdłuż profilów, biegnących od nowych lądów wgłąb zbiorników wodnych.
Pozwoliło to na ocenę zmiany jakości wód wraz ze zwiększaniem odległości od lądu oraz wraz ze zwiększaniem głębokości.
```{r tbl-datainfo, echo=FALSE, warning=FALSE, message=FALSE}
#| label: tbl-data_info
#| echo: false
#| tbl-cap: "Informacje o wykorzystanych danych oraz długości profilu. W tabeli podano lata, dla których pozyskano obrazy satelitarne. Zawarto także ilość dostępnych zdjęć, oraz ile z nich zostało wykorzystane w badaniach. Umieszczono również informacje o rodzaju satelity, które wykonały zdjęcia. W tabeli zawarto również długość profilu w metrach, wzdłuż którego próbkowano wartości wskaźników spektralnych oraz głębokości zbiornika."

aois <- data.frame(
  c("Dubaj, ZEA", "Lagos, Nigeria", "Limon, Kostaryka", "Singapur", "Szanghaj, Chiny"),
  c("Landsat 7", "Landsat 7 i 8", "Landsat 8", "Landsat 5 i 7", "Landsat 7"),
  c("2002 - 2012", "2007 - 2020", "2014 - 2020", "1993 - 2005", "2000 - 2008"),
  c("410", "465", "316", "337", "759"),
  c("45", "51", "27", "46", "39"),
  c("22149 m", "7654 m", "6853 m", "9479 m", "15134 m")
)
knitr::kable(aois, format = "latex", booktabs = TRUE, linesep = "", col.names = c("obszar badań", "satelita", "okres badań", "liczba dostępnych zdjęć", "liczba wybranych zdjęć", "długość profilu"))  |> 
  kableExtra::column_spec(4, width = "2cm") |>  
  kableExtra::column_spec(5, width = "2cm")
```
