project:
  type: book
  output-dir: docs

title: "Ocena wpływu tworzenia nowych lądów na jakość wód przy wykorzystaniu danych teledetekcyjnych"
titleeng: "Assessment of the impact of land reclamation on water quality using remote sensing data"
lang: pl
language:
  pl:
    crossref-fig-title: "Rycina"
    crossref-tab-title: "Tabela"
    crossref-sec-prefix: "Podrozdział"
degreetype: "Praca magisterska" #"Engineer's thesis"
author: "Mateusz Rydzik"
major: "Geoinformacja" #"Geoinformation"
albumid: "455820"
year: "2024"

book:
  output-file: "mrydzik"
  chapters:
    - index.qmd
    #- 00-oswiadczenie.qmd
    #- 00-abstrakt.qmd
    - 01-roz1.qmd
    - 02-roz2.qmd
    - 03-roz3.qmd
    - 04-roz4.qmd
    - 05-roz5.qmd
    - 06-roz6.qmd

bibliography: thesis.bib, packages.bib

format:
  pdf:
    template: amuthesis.tex
    keep-tex: true
    pdf-engine: pdflatex
    cite-method: biblatex
    fig-height: 3.8
    fig-width: 6.3
    fig-asp: 0.618  # 1 / phi
    fig-pos: 't'
    number-sections: true
