project:
  type: book
  output-dir: docs

title: "Mój tytuł"
titleeng: "My title"
lang: pl
language:
  pl:
    crossref-fig-title: "Rycina"
    crossref-tab-title: "Tabela"
    crossref-sec-prefix: "Podrozdział"
degreetype: "Praca inżynierska" #"Engineer's thesis"
author: "Imię Nazwisko"
major: "Geoinformacja" #"Geoinformation"
albumid: "000000"
year: "2028"

book:
  output-file: "imienazwisko"
  chapters:
    - index.qmd
    #- 00-oswiadczenie.qmd
    #- 00-abstrakt.qmd
    - 01-roz1.qmd
    - 02-roz2.qmd
    - 03-roz3.qmd
    - 04-roz4.qmd
    - 05-roz5.qmd
    - 06-roz6.qmd

bibliography: thesis.bib, packages.bib

format:
  pdf:
    template: amuthesis.tex
    keep-tex: true
    pdf-engine: pdflatex
    cite-method: biblatex
    fig-height: 3.8
    fig-width: 6.3
    fig-asp: 0.618  # 1 / phi
    fig-pos: 't'
    number-sections: true
