# Streszczenie {.unnumbered}

**Abstrakt**

Tworzenie nowych lądów polega na sztucznym przekształcaniu obszarów wodnych w tereny lądowe.
Procesy te wpływają na ekosystemy wodne, stanowiąc potencjalne zagrożenie dla występujących w nich organizmów.
Wzrost liczby ludności, zamieszkującej wybrzeża może doprowadzić do nasilenia się procesów tworzenia nowych lądów.
Celem pracy jest ocena potencjalnego wpływu procesów tworzenia nowych obszarów lądowych na jakość pobliskich wód.
Do oceny jakości wód wykorzystane zostały wskaźniki spektralne, obliczone przy wykorzystaniu zdjęć satelitarnych.
Wskaźniki te opisują zmiany dwóch parametrów jakości wód: stężęń chlorofilu a i zawiesiny.
Badania przeprowadzono dla pięciu obszarów, na których powstały nowe lądy: Dubaj (Zjednoczone Emiraty Arabskie), Lagos (Nigeria), Limon (Kostaryka), Singapur i Szanghaj (Chiny).
Wskaźniki spektralne wykryły znaczące zmiany jakości wód na obszarach badań w trakcie tworzenia nowych lądów.
Konstrukcja nowych lądów doprowadziła do spadku stężenia chlorofilu a w Dubaju, Limon i Singapurze.
Wzrost stężęnia chlorofilu a odnotowano w Lagos i Szanghaju.
Podczas trwania budowy nowych obszarów lądowych, w Dubaju, Limon i Szanghaju zaobserwowano wzrost stężenia zawiesiny w wodzie.
W Lagos i Singapurze wykryto długookresowy spadek stężenia zawiesiny.

Słowa kluczowe: (wskaźniki spektralne, obrazy satelitarne, jakość wód, tworzenie lądów)

**Abstract**

Land reclamation involves the artificial transformation of water areas into land areas.
These processes affect water ecosystems, posing potential threats to the organisms living within them.
The increase in coastal population may lead to an intensification of land reclamation processes.
The aim of this study is to assess the potential impact of land reclamation processes on the quality of nearby waters.
Spectral indices, calculated using satellite images, were used to assess water quality.
These indices describe changes in two water quality parameters: chlorophyll-a concentration and suspended matter concentration.
The study was conducted in five areas where new lands have been created: Dubai (United Arab Emirates), Lagos (Nigeria), Limon (Costa Rica), Singapore, and Shanghai (China).
Spectral indices detected significant changes in water quality in the study areas during the land reclamation.
The construction of new lands led to a decrease in chlorophyll-a concentration in Dubai, Limon, and Singapore.
An increase in chlorophyll-a concentration was observed in Lagos and Shanghai.
During the construction of new land areas, an increase in suspended matter concentration in the water was observed in Dubai, Limon, and Shanghai.
In Lagos and Singapore, a long-term decrease in suspended matter concentration was detected.

Keywords: (spectral indices, satellite images, water quality, land reclamation)

\newpage

\setstretch{1.2}\sf\tighttoc\doublespacing
